name: Generate NZPortable Nightlies.
on:
  schedule:
  - cron: 0 7 * * *
  workflow_dispatch:
  
jobs:
  Generate-Nightly:
    runs-on: ubuntu-latest
    container:
      image: sharkwouter/pspdev
    steps:
      - uses: actions/checkout@v4
      - name: Get apt ready
        run: |
          apt update
          apt install -y zip unzip wget curl git jq
      - name: Assemble Archives
        continue-on-error: false
        working-directory: ./
        run: |
          ./generate-nightly.sh ${{ secrets.GITHUB_TOKEN }}
      - name: Get Build Date
        id: date
        run: echo "tag_name=$(cat release_version.txt)" >> $GITHUB_ENV
      - name: Delete Old Release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true
          tag_name: ${{ env.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        continue-on-error: true
        id: attempt-1
        with:
          name: ${{ env.tag_name }}
          tag_name: nightly
          body_path: changes.txt
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./out/nzportable-3ds.zip
            ./out/nzportable-linux32.zip
            ./out/nzportable-linux64.zip
            ./out/nzportable-linuxarm64.zip
            ./out/nzportable-linuxarmhf.zip
            ./out/nzportable-psp-32mb.zip
            ./out/nzportable-psp-64mb.zip
            ./out/nzportable-switch.zip
            ./out/nzportable-vita.zip
            ./out/nzportable-win32.zip
            ./out/nzportable-win64.zip
            ./out/build-version.txt
      - name: Release attempt 2
        uses: softprops/action-gh-release@v1
        continue-on-error: true
        id: attempt-2
        if: steps.attempt-1.outcome == 'failure'
        with:
          name: ${{ steps.date.outputs.date }}
          tag_name: nightly
          body_path: changes.txt
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./out/nzportable-3ds.zip
            ./out/nzportable-linux32.zip
            ./out/nzportable-linux64.zip
            ./out/nzportable-linuxarm64.zip
            ./out/nzportable-linuxarmhf.zip
            ./out/nzportable-psp-32mb.zip
            ./out/nzportable-psp-64mb.zip
            ./out/nzportable-switch.zip
            ./out/nzportable-vita.zip
            ./out/nzportable-win32.zip
            ./out/nzportable-win64.zip
            ./out/build-version.txt
      - name: Release attempt 3
        uses: softprops/action-gh-release@v1
        continue-on-error: true
        id: attempt-3
        if: steps.attempt-2.outcome == 'failure'
        with:
          name: ${{ steps.date.outputs.date }}
          tag_name: nightly
          body_path: changes.txt
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./out/nzportable-3ds.zip
            ./out/nzportable-linux32.zip
            ./out/nzportable-linux64.zip
            ./out/nzportable-linuxarm64.zip
            ./out/nzportable-linuxarmhf.zip
            ./out/nzportable-psp-32mb.zip
            ./out/nzportable-psp-64mb.zip
            ./out/nzportable-switch.zip
            ./out/nzportable-vita.zip
            ./out/nzportable-win32.zip
            ./out/nzportable-win64.zip
            ./out/build-version.txt
      - name: Release attempt 4
        uses: softprops/action-gh-release@v1
        continue-on-error: true
        id: attempt-4
        if: steps.attempt-3.outcome == 'failure'
        with:
          name: ${{ steps.date.outputs.date }}
          tag_name: nightly
          body_path: changes.txt
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./out/nzportable-3ds.zip
            ./out/nzportable-linux32.zip
            ./out/nzportable-linux64.zip
            ./out/nzportable-linuxarm64.zip
            ./out/nzportable-linuxarmhf.zip
            ./out/nzportable-psp-32mb.zip
            ./out/nzportable-psp-64mb.zip
            ./out/nzportable-switch.zip
            ./out/nzportable-vita.zip
            ./out/nzportable-win32.zip
            ./out/nzportable-win64.zip
            ./out/build-version.txt
      - name: Release attempt 5
        uses: softprops/action-gh-release@v1
        continue-on-error: false
        id: attempt-5
        if: steps.attempt-4.outcome == 'failure'
        with:
          name: ${{ steps.date.outputs.date }}
          tag_name: nightly
          body_path: changes.txt
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./out/nzportable-3ds.zip
            ./out/nzportable-linux32.zip
            ./out/nzportable-linux64.zip
            ./out/nzportable-linuxarm64.zip
            ./out/nzportable-linuxarmhf.zip
            ./out/nzportable-psp-32mb.zip
            ./out/nzportable-psp-64mb.zip
            ./out/nzportable-switch.zip
            ./out/nzportable-vita.zip
            ./out/nzportable-win32.zip
            ./out/nzportable-win64.zip
            ./out/build-version.txt

  deploy-to-itch:
    name: Deploy to itch.io
    if: github.ref == 'refs/heads/main' && github.repository_owner == 'nzp-team'
    runs-on: ubuntu-latest
    needs:
      - Generate-Nightly
    steps:
      - name: Install WGET
        run: |
          sudo apt update && sudo apt install -y wget
      - name: Download data
        run: |
          wget https://github.com/nzp-team/nzportable/releases/download/nightly/build-version.txt
          wget https://github.com/nzp-team/nzportable/releases/download/nightly/nzportable-3ds.zip
          wget https://github.com/nzp-team/nzportable/releases/download/nightly/nzportable-linux32.zip
          wget https://github.com/nzp-team/nzportable/releases/download/nightly/nzportable-linux64.zip
          wget https://github.com/nzp-team/nzportable/releases/download/nightly/nzportable-linuxarm64.zip
          wget https://github.com/nzp-team/nzportable/releases/download/nightly/nzportable-linuxarmhf.zip
          wget https://github.com/nzp-team/nzportable/releases/download/nightly/nzportable-psp-32mb.zip
          wget https://github.com/nzp-team/nzportable/releases/download/nightly/nzportable-psp-64mb.zip
          wget https://github.com/nzp-team/nzportable/releases/download/nightly/nzportable-switch.zip
          wget https://github.com/nzp-team/nzportable/releases/download/nightly/nzportable-vita.zip
          wget https://github.com/nzp-team/nzportable/releases/download/nightly/nzportable-win32.zip
          wget https://github.com/nzp-team/nzportable/releases/download/nightly/nzportable-win64.zip
      - name: Upload to itch.io - Nintendo 3DS
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: nzportable-3ds.zip
          itchUsername: nzp-team
          itchGameId: nazi-zombies-portable
          buildChannel: 3ds
          buildNumberFile: build-version.txt
      - name: Upload to itch.io - Linux 32-Bit
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: nzportable-linux32.zip
          itchUsername: nzp-team
          itchGameId: nazi-zombies-portable
          buildChannel: linux-x86
          buildNumberFile: build-version.txt
      - name: Upload to itch.io - Linux 64-Bit
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: nzportable-linux64.zip
          itchUsername: nzp-team
          itchGameId: nazi-zombies-portable
          buildChannel: linux-x86_64
          buildNumberFile: build-version.txt
      - name: Upload to itch.io - Linux ARM64
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: nzportable-linuxarm64.zip
          itchUsername: nzp-team
          itchGameId: nazi-zombies-portable
          buildChannel: linux-arm64
          buildNumberFile: build-version.txt
      - name: Upload to itch.io - Linux ARMhf
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: nzportable-linuxarmhf.zip
          itchUsername: nzp-team
          itchGameId: nazi-zombies-portable
          buildChannel: linux-armhf
          buildNumberFile: build-version.txt
      - name: Upload to itch.io - PlayStation Portable 32mB
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: nzportable-psp-32mb.zip
          itchUsername: nzp-team
          itchGameId: nazi-zombies-portable
          buildChannel: psp-1000
          buildNumberFile: build-version.txt
      - name: Upload to itch.io - PlayStation Portable 64mB
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: nzportable-psp-64mb.zip
          itchUsername: nzp-team
          itchGameId: nazi-zombies-portable
          buildChannel: psp-2000
          buildNumberFile: build-version.txt
      - name: Upload to itch.io - Nintendo Switch
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: nzportable-switch.zip
          itchUsername: nzp-team
          itchGameId: nazi-zombies-portable
          buildChannel: switch
          buildNumberFile: build-version.txt
      - name: Upload to itch.io - PlayStation VITA
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: nzportable-vita.zip
          itchUsername: nzp-team
          itchGameId: nazi-zombies-portable
          buildChannel: vita
          buildNumberFile: build-version.txt
      - name: Upload to itch.io - Windows 32-bit
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: nzportable-win32.zip
          itchUsername: nzp-team
          itchGameId: nazi-zombies-portable
          buildChannel: windows-x86
          buildNumberFile: build-version.txt
      - name: Upload to itch.io - Windows 64-bit
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: nzportable-win64.zip
          itchUsername: nzp-team
          itchGameId: nazi-zombies-portable
          buildChannel: windows-x86_64
          buildNumberFile: build-version.txt

